"""
The Compass Engine — Red Team Tactical & Strategic Next-Step Advisor.

Synthesizes ScanResult findings, MITRE ATT&CK mappings, service versions,
credentials, and privesc paths to generate actionable tactical directives for red teamers:
    1. Assessment of current attack phase / kill-chain positioning.
    2. Ranked highest-value target vectors.
    3. Specific recommended commands & tool invocation templates.
    4. Lateral movement and pivoting suggestions.
    5. Defensive remediation priorities for blue team.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any

from vigil.ai.brain import AIBrain
from vigil.ai.prompts import RED_TEAM_COMPASS_SCHEMA, RED_TEAM_COMPASS_SYSTEM
from vigil.engine.mitre_attack import match_log_to_techniques, suggest_next_tactics
from vigil.models import FindingCategory, ScanResult, Severity

logger = logging.getLogger("vigil.engine.compass")


@dataclass
class TacticalRecommendation:
    """A specific next-step action recommended by the Compass."""

    priority: int
    title: str
    phase: str
    description: str
    suggested_command: str = ""
    tool: str = ""
    target: str = ""


@dataclass
class CompassReport:
    """Complete strategic advice generated by the Compass Engine."""

    current_kill_chain_phase: str = "Reconnaissance"
    threat_level: str = "MEDIUM"
    summary_narrative: str = ""
    mitre_techniques_detected: list[dict[str, Any]] = field(default_factory=list)
    suggested_next_tactics: list[str] = field(default_factory=list)
    recommendations: list[TacticalRecommendation] = field(default_factory=list)
    pivot_opportunities: list[str] = field(default_factory=list)


class CompassEngine:
    """
    Analyzes ScanResult objects and generates actionable tactical direction.
    Uses AI brain enrichment when available (Gemini / OpenAI / Ollama).
    """

    def __init__(self, ai_brain: AIBrain | None = None):
        self.ai_brain = ai_brain

    def generate_report(self, scan_result: ScanResult) -> CompassReport:
        report = CompassReport()

        # 1. Heuristic Kill-Chain Positioning
        has_creds = len(scan_result.credentials) > 0
        has_privesc = len(scan_result.privesc_paths) > 0
        has_critical = scan_result.critical_count > 0

        if has_privesc or any(f.category == FindingCategory.PRIVILEGE_ESCALATION for f in scan_result.findings):
            report.current_kill_chain_phase = "Privilege Escalation"
            report.threat_level = "CRITICAL"
        elif has_creds or any(f.category == FindingCategory.BRUTE_FORCE for f in scan_result.findings):
            report.current_kill_chain_phase = "Credential Access"
            report.threat_level = "HIGH" if has_creds else "MEDIUM"
        elif scan_result.services or any(f.category == FindingCategory.VULNERABILITY for f in scan_result.findings):
            report.current_kill_chain_phase = "Initial Access"
            report.threat_level = "HIGH" if has_critical else "MEDIUM"
        else:
            report.current_kill_chain_phase = "Reconnaissance"
            report.threat_level = "LOW"

        # 2. MITRE ATT&CK Mapping
        raw_text_corpus = []
        for finding in scan_result.findings:
            raw_text_corpus.append(f"{finding.title} {finding.description}")
            for entry in finding.evidence:
                raw_text_corpus.append(entry.raw_line)

        combined_text = "\n".join(raw_text_corpus)
        report.mitre_techniques_detected = match_log_to_techniques(combined_text)
        report.suggested_next_tactics = suggest_next_tactics(report.current_kill_chain_phase)

        # 3. Base Heuristic Recommendations Generator
        recs: list[TacticalRecommendation] = []
        rec_id = 1

        if scan_result.credentials:
            for cred in scan_result.credentials[:3]:
                cmd = f"hydra -l {cred.username} -p '{cred.secret}' ssh://<TARGET_IP>" if cred.secret else f"ssh {cred.username}@<TARGET_IP>"
                recs.append(
                    TacticalRecommendation(
                        priority=rec_id,
                        title=f"Validate Extracted Credential ({cred.username})",
                        phase="Initial Access / Lateral Movement",
                        description=f"Credential for user '{cred.username}' discovered ({cred.context}). Test across open administration ports.",
                        suggested_command=cmd,
                        tool="ssh / hydra",
                        target=cred.source_ip or "<TARGET_IP>",
                    )
                )
                rec_id += 1

        for service in scan_result.services:
            if service.cve_matches:
                cve = service.cve_matches[0]
                recs.append(
                    TacticalRecommendation(
                        priority=rec_id,
                        title=f"Exploit Service Vulnerability ({service.service_name} {service.version})",
                        phase="Initial Access / Execution",
                        description=f"Discovered {service.service_name} {service.version} vulnerable to {cve.get('cve_id')} (CVSS {cve.get('cvss')}).",
                        suggested_command=f"searchsploit {service.service_name} {service.version}",
                        tool="searchsploit / msfconsole",
                        target=f"{service.host}:{service.port}",
                    )
                )
                rec_id += 1

        for priv in scan_result.privesc_paths[:3]:
            recs.append(
                TacticalRecommendation(
                    priority=rec_id,
                    title=f"Execute Privilege Escalation via {priv.technique}",
                    phase="Privilege Escalation",
                    description=f"Discovered privilege escalation route via {priv.technique}. Risk level: {priv.risk}.",
                    suggested_command=priv.command,
                    tool="bash / GTFOBins",
                    target="Local Host",
                )
            )
            rec_id += 1

        if not recs:
            recs.append(
                TacticalRecommendation(
                    priority=1,
                    title="Perform Deep Service & Port Enumeration",
                    phase="Reconnaissance",
                    description="Perform full-port scan and service version fingerprinting across all open TCP/UDP ports.",
                    suggested_command="nmap -sV -sC -p- -oA full_scan <TARGET_IP>",
                    tool="nmap",
                    target="<TARGET_IP>",
                )
            )

        report.recommendations = recs

        # 4. AI Deep Directive Enrichment (If LLM provider is configured)
        if self.ai_brain and self.ai_brain.provider:
            try:
                ai_report = self._enrich_with_ai(scan_result)
                if ai_report:
                    report.current_kill_chain_phase = ai_report.get("kill_chain_phase", report.current_kill_chain_phase)
                    report.threat_level = ai_report.get("threat_level", report.threat_level)
                    report.summary_narrative = ai_report.get("strategic_summary", "")

                    # Merge AI tactical recommendations
                    ai_tactics = ai_report.get("tactical_next_steps", [])
                    if ai_tactics:
                        ai_recs = []
                        for item in ai_tactics:
                            ai_recs.append(
                                TacticalRecommendation(
                                    priority=item.get("priority", 1),
                                    title=item.get("title", ""),
                                    phase=item.get("phase", "Reconnaissance"),
                                    description=item.get("description", ""),
                                    suggested_command=item.get("command_template", ""),
                                    tool=item.get("tool", ""),
                                    target=item.get("target", "<TARGET_IP>"),
                                )
                            )
                        report.recommendations = ai_recs

                    # Merge AI MITRE techniques
                    ai_mitre = ai_report.get("mitre_techniques", [])
                    if ai_mitre:
                        report.mitre_techniques_detected.extend(ai_mitre)

            except Exception as e:
                logger.error(f"AI Red Team Compass enrichment failed: {e}")

        if not report.summary_narrative:
            report.summary_narrative = (
                f"Vigil Compass Assessment: Target is at '{report.current_kill_chain_phase}' phase "
                f"(Threat Level: {report.threat_level}). Identified {len(report.recommendations)} tactical "
                f"actions and {len(report.mitre_techniques_detected)} MITRE ATT&CK technique signatures."
            )

        return report

    def _enrich_with_ai(self, scan_result: ScanResult) -> dict[str, Any] | None:
        """Call AI provider with RED_TEAM_COMPASS_SYSTEM prompt and schema."""
        target_summary = []
        for s in scan_result.services[:10]:
            target_summary.append(f"Host: {s.host} | Port: {s.port}/{s.protocol} | Service: {s.service_name} | Version: {s.version}")

        for f in scan_result.findings[:10]:
            target_summary.append(f"Finding: {f.title} ({f.severity.value}) - {f.description[:200]}")

        payload = (
            f"TARGET SCAN SUMMARY:\n"
            f"Files Analyzed: {', '.join(scan_result.files_analyzed)}\n"
            f"Discovered Services & Ports:\n" + "\n".join(target_summary) + "\n\n"
            f"Please generate the Red Team Tactical Directives."
        )

        return self.ai_brain.structured_output(
            system_prompt=RED_TEAM_COMPASS_SYSTEM,
            user_content=payload,
            response_schema=RED_TEAM_COMPASS_SCHEMA,
        )
